# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Tox Unit Tests
# env:
#   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_ID }}

on:
  push:
    branches: [ prod ]
  pull_request:
    branches: [ prod ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: Install test dependencies
      run: |
        python -m pip install --upgrade pip tox pytest flake8
    # - name: Test with tox
    #   run: |
    #     tox
    - name: Lint with Flake8
      run: |
        flake8
      continue-on-error: true
    - name: Test Docker build
      run: |
        docker build -t eagle-vision .
        docker run -d -p 8501:8501 eagle-vision